name: Github Actions - Types Pull Resquest 
run-name: Running - ${{ github.event_name }}
on:
  pull_request:
    types:
        - opened
        - reopened
        - closed
jobs:
  on-push:
    runs-on:   ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Types Pull request on branches"