name: Github Actions - Workflow Dispatch 
run-name: Running - ${{ github.event_name }}
on: [workflow_dispatch]
jobs:
  on-push:
    runs-on:   ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Workflow dispatch basic"