name: Github Actions - Push template basic
run-name: Running - ${{ github.event_name }}
on: 
  push:
    branches:
      - develop
jobs:
  on-push:
    runs-on:   ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentáro do workflow PUSH"
