name: Github Actions -Choice Workflow Dispatch 
run-name: Running - ${{ github.event_name }}
on: 
  workflow_dispatch:
    inputs:
        browser:
            description: Selecitone browser
            type: string
jobs:
  on-workflow_dispatch:
    runs-on:   ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Choice Workflow dispatch basic - ${{inputs.browser}}"